---
version: 0.2

phases:
  install:
    commands:
      - echo Entering install phase
  pre_build:
    commands:
      - echo Entering pre-build phase
  build:
    commands:
      - echo Build started ....
      - mvn -f pom.xml compile
      - mvn -f pom.xml package 
  post_build:
    commands:
      - echo Build completed....
artifacts:
  type: zip
  files:
    - appspec.yml
    - script/start_server
    - script/install_dependencies
    - target/sample_webapp.war
